### ISSUE TITLE
Existe el modelo Society

### ISSUE THREAD

**Issue by cparram** [Wolf-usm/wolf-backend#1]
Modelo para registrar sociedades o compañias, como por ejemplo: AES Gener.

Considerar los atributos:
- `name`: Nombre de la sociedad. Ej: Embotelladora Andina
- `alias` o `nemo`: Nemo de la sociedad/cartera: Ej: ANDINA-B.

Se debe valida:
- unicidad tanto de `name` como de `alias` y sus respectivos índices únicos

**Comment by matiasarayac** [comment]
Esto esta listo, era simple así que hice el pull request de inmediato. Además que quería probarlo la verdad jaja.
