### ISSUE TITLE
Existe modelo Tweet

### ISSUE THREAD

**Issue by cparram** [Wolf-usm/wolf-backend#2]
Modelo para tener registro del los twits analizados por wolf.

Atributos:
- `tweet_id`: Id del tuiter
- `polarity`: polaridad del tuit para obtener el score
- `datetime`: fecha y hora del tuit
- `message`: tuit

Considerar además:
- Validar valores fijos para `polarity`: `:negative`, `:positive` y `:neutro` (por default: `:neutro`)
- Validar presencia y unicidad de `tweet_id`
- Relación con el modelo `Society`

**Comment by matiasarayac** [comment]
Ya está listo cesar, revisalo please
